config/routes.rb
ProjectPkm::Application.routes.draw do
  get 'static_pages/about', path: 'tentang-kami', as: 'about'
  get 'static_pages/contact', path: 'kontak', as: 'contact'
  match 'businesses/invest', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new', path: 'daftar', as: 'signup'
  get 'sessions/new', path: 'login', to: 'sessions#new', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :businesses, path: 'ukm'
  resources :categories, path: 'kategori'
  root 'businesses#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show]

  # GET /businesses
  # GET /businesses.json
  def index
    if params[:kategori]
      @businesses = Business.category_name(params[:kategori])
    else
      @businesses = Business.all.order(updated_at: :desc)
    end
    @categories = Category.all.order(name: :asc)
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business_images = @business.business_images.all
  end

  # GET /businesses/new
  def new
    @business = Business.new
    @business_images = @business.business_images.build
  end

  # GET /businesses/1/edit
  def edit
    @business_images = @business.business_images.build
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        if params[:business_images]
          params[:business_images]['image'].each do |img|
            @business_image = @business.business_images.create!(image: img, business_id: @business.id)
          end
        end
        flash[:success] = 'Profil UKM berhasil dibuat.'
        format.html { redirect_to @business }
        format.json { render action: 'show', status: :created, location: @business }
      else
        format.html { render action: 'new' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        flash[:success] = 'Profil UKM berhasil diperbarui.'
        format.html { redirect_to @business }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end

  def invest
    c = Curl::Easy.http_post("https://api.sandbox.veritrans.co.id/v2/charge")
    render json: c.body_str
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :established, :email, :location, :category_id, :user_id, :photo, :days_left, :phone, :target, :received, business_images_attributes: [:id, :business_id, :image])
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, html: { multipart: true, class: 'form-horizontal' } do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Nama', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Kategori', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.collection_select(:category_id, Category.all, :id, :name) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Deskripsi', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Tanggal didirikan', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.date_select :established, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Lokasi', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_area :location, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Email', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Nomor Telefon', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Batas pengumpulan modal', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.date_select :days_left, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Jumlah dana yang sudah dikumpulkan', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :received, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Target dana', class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :target, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Logo', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :photo %>
    </div>
  </div>
  <div class="form-group">
    <%= f.fields_for :business_images, @business.business_images do |img| %>
      <%= img.label :image, class: "col-sm-2 control-label" %>
      <% if img.object.image %>
        <%= image_tag img.object.image.url %>
      <% end %>
      <%= img.file_field :image, multiple: true, name: "business_images[image][]", class: "col-sm-4" %>
    <% end %>
  </div>
  <%= f.hidden_field(:user_id, value: current_user.id) %>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit(class: "btn btn-default btn-primary") %>
    </div>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Ubah profil UKM</h1>

<%= render 'form' %>

app/views/businesses/index.html.erb
<div id="category-list" class="col-md-2 col-xs-6">
  <h2>Kategori</h2>
  <ul>
    <% @categories.each do |cat| %>
    <li><a href="/ukm?kategori=<%= cat.name %>"><%= cat.name %></a></li>
    <% end %>
    <li><a href="/">Semua</a></li>
  </ul>
</div>

<div id="ukm-list" class="col-md-10 col-xs-12">
  <h1> UKM</h1>
  <% @businesses.each do |business| %>
    <div class="kotakan-ukm">
      <div class="item-ukm">
        <div class="img-thumbnail"><%= image_tag(business.photo.url, alt: "#{business.name} logo") %></div>
        <p><h2><%= link_to business.name, business %></h2><!-- <div class="hr-divider"></div> --></p>
        <p style="text-align: justify; padding-right: 50px;"><%= truncate(business.description, length: 500, separator: ' ') { link_to ' baca selengkapnya', business} %></p>
      </div>
      <div class="styled">
        <progress value="<%= business.received %>" max="<%= business.target %>"></progress>
      </div>
      <div class="kotakan">
        <div class="persen">
          <p><strong><%= business.received*100/business.target %>%</strong></p>
          <p><h5>Progress</h5></p>
        </div>  <div class="vr-divider"></div>
        <div class="terkumpul">
          <p><strong><%= number_to_currency(business.received) %></strong></p>
          <p><h5>Terkumpul</h5></p>
        </div>
        <div class="vr-divider2"></div>
        <div class="hari">
          <p><strong>
            <% if business.days_left > Time.now %>
              <%= ((business.days_left - Time.now)/3600/24).round(0) %>
            <% else %>
              <%= 0 %>
            <% end %>
            </strong></p>
          <p><h5>Hari Tersisa</h5></p>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/businesses/new.html.erb
<div class="kotakan-daftar">
<h1>Buat profil UKM</h1>
</div>

<div class="kotakan-form">
<%= render 'form' %>
</div>

app/views/businesses/show.html.erb
<div id="ukm-images-carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% for i in 0..@business_images.count-1 %>
      <% if i == 0 %>
        <li data-target="#ukm-images-carousel" data-slide-to="<%= i %>" class="active"></li>
      <% else %>
        <li data-target="#ukm-images-carousel" data-slide-to="<%= i %>"></li>
      <% end %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @business_images.each do |img| %>
      <div class="item<%= ' active' if @business_images.first == img %>">
        <img src="<%= img.image.url(:thumb) %>" alt="<%= img.image.filename %>">
        <div class="carousel-caption">
          ...
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#ukm-images-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#ukm-images-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<div class="content-ukm">

	<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#deskripsi" data-toggle="tab">Deskripsi</a></li>
    <li><a href="#profil-owner" data-toggle="tab">Owner</a></li>
    <li><a href="#investor" data-toggle="tab">Investor</a></li>
    <li><a href="#komentar" data-toggle="tab">Komentar</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade in active" id="deskripsi">
    	<div class="ukm-desc">
        <div class="img-profil">
          <%= image_tag @business.photo.url %>
        </div>

    		<div class="profil-title">
    		  <h1><%= @business.name %><br><small><%= @business.category.name %></small></h1>
    		</div>

    		<div class="profil-desc">
    		  <p><%= @business.description %></p>
    		  <p style="font-style: italic; float: right;">Ukm dibuat pada <%= @business.established.to_formatted_s(:long) %></p>
    		</div>

    		<div class="profil-contact">
          <h2>Kontak</h2>
    		  <p>Lokasi usaha : <%= @business.location %></p>
    		  <p>Nomor telp/HP : <%= @business.phone %></p>
    		  <p>Email : <%= @business.email %></p>
    		</div>

    		<% if @business.user == current_user %>
      		<%= link_to 'Edit', edit_business_path(@business) %>
          <%= link_to 'Hapus', business_path, method: :delete, data: { confirm: 'Anda yakin ingin menghapus usaha anda?' } %>
    		<% end %>
  	  </div>
    </div>

    <div class="tab-pane fade" id="profil-owner">
    	<div class="content-wrapper">
        <div class="avatar-profile">
      		<%= image_tag @business.user.avatar.url %>
        </div>
        <div>
          <p><%= link_to @business.user.name, @business.user %></p>
          <p><%= @business.user.email %></p>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="investor">
    	<div class="content-wrapper">
      		<h3>Daftar Investor</h3>
          <p>Belum ada investor</p>
      </div>
    </div>
    <div class="tab-pane fade" id="komentar">
    	<div class="content-wrapper">
    		<h3>Komentar</h3>
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'modalin'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
      </div>
    </div>
  </div>

	<div class="ukm-stats">
		<div class="styled">
			<progress value="<%= @business.received %>" max="<%= @business.target %>"></progress>
		</div>

      <div class="persen">
        <p><strong><%= @business.received*100/@business.target %>%</strong></p>
        <p><h5>Progress</h5></p>
      </div>
      <div class="vr-divider2"></div>
      <div class="terkumpul">
        <p><strong><%= number_to_currency(@business.received) %></strong></p>
        <p><h5>Terkumpul</h5></p>
      </div>
      <div class="vr-divider2"></div>
      <div class="hari">
        <p><strong>
          <% if @business.days_left > Time.now %>
            <%= ((@business.days_left - Time.now)/3600/24).round(0) %>
          <% else %>
            <%= 0 %>
          <% end %>
        </strong></p>
        <p><h5>Hari Tersisa</h5></p>
      </div>

    <!-- <div class="ukm-profit">
  		<h3>Keuntungan UKM</h3>
  		<p>1 juta / tahun</p>
	</div> -->

	<div class="ukm-reward">
		<h3>Reward</h3>
		<h4>Bronze</h4>
		<h4>Gold</h4>
		<h4>Rhodium</h4>
	</div>
  <%= button_to "Klik untuk Modalin", { controller: "businesses", action: "invest", business: @business } %>
  <!-- <form action="https://api.sandbox.veritrans.co.id/v2/charge" method="post">
    <button class="btn btn-primary btn-lg" style="float: right"><small><p>Klik untuk</p></small>Modalin</button>
    <input type="submit" name="invest" value="invest">
  </form> -->

	</div>



	<script>
  $(function () {
    $('#myTab a:first').tab('show')
  })
</script>

</div>