config/routes.rb
ProjectPkm::Application.routes.draw do
  get 'static_pages/about', path: 'tentang-kami', as: 'about'
  get 'static_pages/contact', path: 'kontak', as: 'contact'
  match 'businesses/invest', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new', path: 'daftar', as: 'signup'
  get 'sessions/new', path: 'login', to: 'sessions#new', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :businesses, path: 'ukm'
  resources :categories, path: 'kategori'
  root 'businesses#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :businesses, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6}

  has_attached_file :avatar, url: "/assets/avatars/:id/:basename.:extension", path: ":rails_root/public/assets/avatars/:id/:basename.:extension", default_url: "/assets/avatars/missing.gif"
  validates_attachment_size :avatar, less_than: 500.kilobytes
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @businesses = Business.all.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login @user
        format.html { redirect_to @user }
        format.json { render action: 'show', status: :created, location: @user }
        flash[:success] = 'User was successfully created.';
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { head :no_content }
        flash[:success] = 'User was successfully updated.'
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :birthday, :password, :password_confirmation, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal", multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Nama Lengkap', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Email', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :email, class: "col-sm-4 form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Password', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: "col-sm-4 form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Ulangi Password', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password_confirmation, class: "col-sm-4 form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Tanggal Lahir', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :birthday, start_year: 1975 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Avatar', class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit(class: "btn btn-default btn-primary") %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="kotakan-daftar">
<h1>Ubah Profil Pengguna</h1>
</div>

<div class="kotakan-form">
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.birthday %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user == current_user %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="kotakan-daftar">
<h1>Buat akun baru</h1>
</div>

<div class="kotakan-form">
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="profil">
  <div class="avatar-profile">
    <%= image_tag @user.avatar.url %>
  </div>

  <div class="profil-pengguna">
    <h3>Profil</h3>
    <p>
      <strong>Nama:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Tanggal lahir:</strong>
      <%= @user.birthday.to_formatted_s(:long) %>
    </p>
    <% if logged_in? && current_user == @user %>
      <p>
        <%= link_to 'Buat usaha', new_business_path %>
      </p>
    <% end %>
  </div>
</div>

<div class="usaha-lain">
  <h3>Usaha milik <%= @user.name %></h3>
  <% @businesses.each do |business| %>
      <div class="usaha-thumbnail">
        <%= image_tag business.photo.url %>
        <%= link_to business.name, business %>
      </div>
      <p>
      </p>
  <% end %>
</div>