config/routes.rb
ProjectPkm::Application.routes.draw do
  get 'static_pages/about', path: 'tentang-kami', as: 'about'
  get 'static_pages/contact', path: 'kontak', as: 'contact'
  match 'businesses/invest', via: 'post'

  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new', path: 'daftar', as: 'signup'
  get 'sessions/new', path: 'login', to: 'sessions#new', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :businesses, path: 'ukm'
  resources :categories, path: 'kategori'
  root 'businesses#index'

end

app/views/layouts/_footer.html.erb
<footer>
  &copy2014
  <ul class="navbar-right">
    <li><%= link_to 'Tentang Kami', about_path %></li>
    <li><%= link_to 'Kontak', '#' %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for mobile view -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo2.png'), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Beranda', businesses_path %></li>
      <% if logged_in? %>
        <li class="dropdown">
          <a href="<%= user_path(current_user) %>" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profil', current_user %></li>
            <li><%= link_to 'Setting', edit_user_path(current_user) %></li>
            <li><%= link_to 'Keluar', logout_path, method: 'delete' %></li>
          </ul>
        </li>
      <% else %>
        <li class="daftar"> <%= link_to 'Daftar', signup_path %></li>
        <li class="masuk"> <%= link_to 'Masuk', login_path %></li>
      <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Modalin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
  <!-- <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'> -->
</head>
<body>
<div class="wrapper">
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key,value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </div>
  

  <%= render 'layouts/footer' %>
</div>

</body>
</html>